import { IUsersData } from "@/sections/users/UserTableRow"

export const _mockUsers: IUsersData[] = [
    { firstName: "Abdulmojeed", lastName: "Ayoola", email: "mojeedayoola58@gmail.com", date: "15/01/2024" },
    { firstName: "Abdulmojeed", lastName: "Ayoola", email: "mojeedayoola58@gmail.com", date: "15/01/2024" },
    { firstName: "Abdulmojeed", lastName: "Ayoola", email: "mojeedayoola58@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    { firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
]
