import { IUsersData } from "@/sections/users/UsersTableRow"

export const _mockUsers: IUsersData[] = [
    {
        userId: "1",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    {
        userId: "2",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    {
        userId: "3",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    { userId: "4", firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    {
        userId: "5",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    { userId: "6", firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    {
        userId: "7",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    { userId: "8", firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    {
        userId: "9",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    { userId: "10", firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    {
        userId: "11",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    { userId: "12", firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    {
        userId: "13",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    { userId: "14", firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    {
        userId: "15",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    { userId: "16", firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    {
        userId: "17",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    { userId: "18", firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
    {
        userId: "19",
        firstName: "Abdulmojeed",
        lastName: "Ayoola",
        email: "mojeedayoola58@gmail.com",
        date: "15/01/2024",
    },
    { userId: "20", firstName: "Hannah", lastName: "Jonathan", email: "hannahjonathan@gmail.com", date: "15/01/2024" },
]
